### ISSUE TITLE
Using extension in route params?

### ISSUE THREAD

**Issue by aeyoll** [routerify/routerify#107]
Hello,
I'm trying to achieve something like this using routerify:

```rust
Router::builder()
     // ...
    .get("/api/:id.source", get_message_source)
    .get("/api/:id.html", get_message_html)
    .get("/api/:id.eml", get_message_eml)
    .get("/api/:id.plain", get_message_plain)
     // ...
```

By doing so, I'm unable to get the `:id` parameter. The following test can replicate the issue:

```rust
#[tokio::test]
async fn can_extract_extension_path_params() {
    const RESPONSE_TEXT: &str = "Hello world";
    let router: Router<Body, routerify::Error> = Router::builder()
        .get("/api/:id.json", |req| async move {
            let id = req.param("id").unwrap(); // Error here:  "called `Option::unwrap()` on a `None` value'"
            assert_eq!(id, "40");
            let (parts, _) = req.into_parts();
            let id = parts.param("id").unwrap();
            assert_eq!(id, "40");
            Ok(Response::new(RESPONSE_TEXT.into()))
        })
        .build()
        .unwrap();
    let serve = serve(router).await;
    let resp = Client::new()
        .request(
            Request::builder()
                .method("GET")
                .uri(format!("http://{}/api/40.json", serve.addr()))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let resp = into_text(resp.into_body()).await;
    assert_eq!(resp, RESPONSE_TEXT.to_owned());
    serve.shutdown();
}
```

Am I doing something wrong, or is it a wider issue?
(I know I can bypass the problem by changing the routes from `/api/:id.source` to `/api/:id/source`, but it'd like to avoid it if possible)
Thanks a lot.

**Comment by rousan** [comment]
You can register a single route at `.get("/api/:idExt")`, then call the corresponding hooks based on the value of `idExt` parameter.

**Comment by aeyoll** [comment]
Hello @rousan. I can do that but in my opinion, the route parsing should be done by the router, not manually. PR #108 fix this issue and has no other impact, can you take a look at it please? It's just a simple change in the PATH_PARAMS_RE regex. It would be a much more elegant solution.
Thanks a lot
