### ISSUE TITLE
Example for Shared State doesn't work

### ISSUE THREAD

**Issue by tolumide-ng** [routerify/routerify#110]
Hello, thank you for the awesome work here.

I noticed there was a previous closed [issue](https://github.com/routerify/routerify/issues/99) related to this and tried using the recommended solution (as stated on the [Readme](https://github.com/routerify/routerify#routerify)) but it didn't solve the problem either.

I am unable to access the shared state from my `controllers`. I have something like this as the `AppState`:

```
struct AppState {
  client: Client,
  db: DbPool,
  vars: Vars,
}
```

and a function passed the router declared like this:

```
pub async fn fn_name(req: Request<Body>) -> TResult<ApiBody> {
  let state = req.data::<AppState>().unwrap();
  ...
}
```

### What do you see ?
<img width="738" alt="Screenshot 2022-02-12 at 21 58 03" src="https://user-images.githubusercontent.com/35481645/153728247-4528f226-4eba-4cfe-9f66-d316d9a48901.png">

### What have you tried?
I followed the examples as specified in [shared_data_and_state](https://github.com/routerify/routerify/blob/master/examples/share_data_and_state.rs) but the issue remains the same.

I tried 2 different approaches for the dependencies in this case: 

1. As specified in the Readme
```
hyper = "0.14"
tokio = { version = "1", features = ["full"] }
routerify = "3"
hyper-tls = "0.5.0"
```

2. My initial deps
```
tokio = { version = "1.15.0", features = ["full"] }
hyper = { version = "0.14.16", features = ["full"]}
routerify = "3.0.0"
```

Iis there something that I might be missing in this case? Thank you in advance

**Comment by ta3pks** [comment]
if you read the error message you shared it tells you the answer already. 
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/9097437/153750414-e5cfbc19-d3d7-4ace-a470-854a9dbeffc5.png">

**Comment by tolumide-ng** [comment]
I totally missed that, thank yiou @NikosEfthias
