### ISSUE TITLE
Session handling (feature request)

### ISSUE THREAD

**Issue by rkfox** [routerify/routerify#12]
I'm not sure if this is within the scope of the project, but the big problem I have using hyper is how to handle sessions since the Response is created separately from the Request. It appears as though request.extensions().get() would be helpful, but there isn't a clean way to connect that to the response to ensure that a cookie is being set since the Request is not available in middleware::post.

**Comment by rousan** [comment]
@rkfox ,  I will add a request meta to middleware::post to get access of the requests header(cookies).
and release soon (maybe on this upcoming weekend).
for more info #10

**Comment by rousan** [comment]
also, check out the new version [1.1.0](https://github.com/routerify/routerify/releases), It got 10x performance improvements.

**Comment by rousan** [comment]
Solved in [v1.1.1](https://github.com/routerify/routerify/releases/tag/v1.1.1).

Now, error response can be generated based on the request info e.g. session managing.
An [example](https://github.com/routerify/routerify/blob/master/examples/error_handling_with_request_info.rs).
For more [info](https://docs.rs/routerify/1.1.1/routerify/index.html#error-handling-with-request-info).
