### ISSUE TITLE
Add basic smoke tests?

### ISSUE THREAD

**Issue by seanpianka** [routerify/routerify#18]
When I've been doing testing of the behavior of this crate, I always need to write a program using it, compile and run it, and use Postman to actually make the HTTP requests myself. Instead of this manual process, could we demonstrate how to automate these tests by adding some basic smoke tests?

Essentially, create a server like the README's example shows inside of a test function:

```rust
#[test]
async fn http_200() {
    let router = routerify::Router::builder()
        .get(
            "/",
            async move |_req| -> Result<hyper::Response<hyper::Body>, Infallible> {
                Ok(hyper::Response::new(hyper::Body::from("hello world")))
            },
        )
        .build()
        .unwrap();
    let service = routerify::RouterService::new(router).unwrap();
    let client = hyper::Client::builder()
        .build::<routerify::RouterService<hyper::Body, Infallible>, hyper::Body>(service);
}
```

However, this does not compile:

```
error[E0277]: the trait bound `routerify::service::router_service::RouterService<hyper::body::body::Body, std::convert::Infallible>: std::clone::Clone` is not satisfied
  --> src/cmd/local/main.rs:86:82
   |
86 |         .build::<routerify::RouterService<hyper::Body, Infallible>, hyper::Body>(service);
   |                                                                                  ^^^^^^^ the trait `std::clone::Clone` is not implemented for `routerify::service::router_service::RouterService<hyper::body::body::Body, std::convert::Infallible>`

error[E0277]: the trait bound `routerify::service::router_service::RouterService<hyper::body::body::Body, std::convert::Infallible>: tower_service::Service<http::uri::Uri>` is not satisfied
  --> src/cmd/local/main.rs:86:82
   |
86 |         .build::<routerify::RouterService<hyper::Body, Infallible>, hyper::Body>(service);
   |                                                                                  ^^^^^^^ the trait `tower_service::Service<http::uri::Uri>` is not implemented for `routerify::service::router_service::RouterService<hyper::body::body::Body, std::convert::Infallible>`
   |
   = help: the following implementations were found:
             <routerify::service::router_service::RouterService<B, E> as tower_service::Service<&hyper::server::tcp::addr_stream::AddrStream>>
   = note: required because of the requirements on the impl of `hyper::client::connect::sealed::Connect` for `routerify::service::router_service::RouterService<hyper::body::body::Body, std::convert::Infallible>`
```

Any advice on how to proceed, @rousan?

**Comment by rousan** [comment]
It does not compile because hyper client doesn't expect our router service, need to take another approach, there will be some libraries to mock client, I guess.

Why don't you join this organization and start contributing?

**Comment by seanpianka** [comment]
I’m happy to contribute, but I figure it will take me a long time to get ramped up on how you’ve designed this crate. I think a big change like this might be simpler and faster for you to implement, no?

**Comment by rousan** [comment]
Let me know if you need any detailed explanation about the crate.

And This writing testcases has nothing to do with this crate, need to use any third party library, need to look at how hyper.rs library does it.

**Comment by seanpianka** [comment]
While having tests is not technically a part of this crate, it’s better to have automated tests. Instead of having to run a server locally and make HTTP requests to your server yourself, you can automate this with tests and make sure everything works just by running `$ cargo test`.

I can experiment by modifying this crate’s code to implement the two traits. Routerify::RouterService needs clone and URI traits, then it can be passed to the hyper client builder and used to make requests programmatically.

**Comment by rousan** [comment]
okay, I will look into this on weekend for sure.

**Comment by seanpianka** [comment]
Can you help me understand why you used unsafe within the RequestService? Why `unsafe { &mut *self.router }` and not just make `Router` derive Clone using Arc/Mutex?

**Comment by seanpianka** [comment]
All I'm really trying to understand is how to call [RequestService::call](https://github.com/routerify/routerify/blob/master/src/service/request_service.rs#L36) directly. 

```rust
    #[tokio::test]
    async fn http_200() {
        let remote_addr = SocketAddr::V4(SocketAddrV4::new(Ipv4Addr::new(127, 0, 0, 1), 80));
        let mut router = router::Router::builder().get("/", hello_world).build().unwrap();
        let mut service = RequestService::new(router, remote_addr).unwrap();
        match service
            .call(hyper::Request::builder().body(Body::from("hello, world!")).unwrap())
            .await
        {
            Ok(res) => {
                println!("{:?}", res);
            }
            Err(e) => {
                println!("{:?}", e);
            }
        }
    }
```

I made `RequestService::new` do all the same initialization that `RouterService::new` does to the  `Router` argument. However, this is failing due to `panicked at 'attempt to subtract with overflow'`.

**Comment by rousan** [comment]
> Can you help me understand why you used unsafe within the RequestService? Why unsafe { &mut *self.router } and not just wrap Router in an Arc/Mutex?

Actually, because of the performance. If I have used `Arc`, it will impact the performance when you will have a lot of simultaneous requests, as the `Arc` manages a concurrent counter to keep track of the current active owners and this counter gets updated only once at a time, so if you got 1k requests, this counter will get updated one by one and other new requests will wait which impacts the performance.

**Comment by seanpianka** [comment]
Makes sense, so the reference counting being atomic is what causes the performance hit, Instead, what if you used a non-thread-safe Rc? Would that be as slow as my previous suggestion?

Do you have any comments or thoughts on making RequestService easier to be directly callable? I’m struggling due to this unsafe mutable pointer code...

**Comment by rousan** [comment]
> Makes sense, so the reference counting being atomic is what causes the performance hit, Instead, what if you used a non-thread-safe Rc? Would that be as slow as my previous suggestion?

`Rc` will make data racing and the compiler won't allow it.

> Do you have any comments or thoughts on making RequestService easier to be directly callable? I’m struggling due to this unsafe mutable pointer code...

Let me see.

**Comment by rousan** [comment]
Hey @seanpianka 
I just added a hello world integration test in `tests/integration.rs` file in `develop` branch, It shows how to write test cases with `routerify`. I will add more later.

**Comment by rousan** [comment]
Now, just copy the support file as a module and start writing your own test cases without creating a separate file.

**Comment by rousan** [comment]
>but using async to spawn the server and then in a different async call send the request, that’s pretty ingenious (I’m not sure I would have figured that out).

Actually, It's just a basic approach if you're familiar with hyper.rs and tokio.rs.

Also, I'm grateful that this crate is growing with new features and improvements day by day.
