### ISSUE TITLE
Middleware with next handler access

### ISSUE THREAD

**Issue by ar3s3ru** [routerify/routerify#22]
The current implementation of middleware is the following:
https://github.com/routerify/routerify/blob/7602b5811e3dc86c00a8a157f74fbd83276b6d06/src/middleware/mod.rs#L19-L26

With the current implementation, a Middleware either runs _before_ the request, or _after_ the request, but there is no full-flow access from the middleware. Which means, handling scenarios like logging the request duration becomes very complicated, because of this:

```
fn middleware(nextHandler) -> handler {
    return |request| -> response {
        let timer = startTimer();
        let response = nextHandler(request);
        let latency = timer.observe();
        // do something with the observed latency
        return response;
    }
}
```

**Comment by rousan** [comment]
Hey @ar3s3ru , the routing middleware system in Routerify is very simple and I have a plan to improve it in future. However, You can achieve the same using pre middleware and post-middleware as follows:

```rust

timer: Timer = <a_global_timer>;

// Attach it as last pre-middleware
fn pre_middleware(request) -> request {
   timer = startTimer();
}

// Attach it as first post middleware
fn post_middleware(response) -> response {
   let latency = timer.observe();
  // do something with the observed latency
}
```

**Comment by ar3s3ru** [comment]
Hey @rousan,

Thanks for the answer. Happy to know that there's a plan to improve the middleware system! In that regard, I wouldn't mind contributing -- especially if you're planning on discussing design strategy on a tracking issue.

As for the snippet you provided, I'm skeptical it would work: the `Timer` has global state, which means that this whole trick won't work as soon as you start having concurrent requests (which is the point of writing web services :wink:)

Another idea I thought about was to create the timer instance in the `pre_middleware` and somehow add the instance to the request data (similar to how you attach the application state to the request). However, as far as I can see, there is no way to modify the state from the `pre_middleware`... Is that correct?

**Comment by gsserge** [comment]
The upcoming 2.0 release will include per request contexts. You can check out the example from https://github.com/routerify/routerify/pull/43 to see how to measure request's duration.
