### ISSUE TITLE
cannot remove x-powered-by header

### ISSUE THREAD

**Issue by NikosEfthias** [routerify/routerify#27]
I am trying to remove x-powered-by header which is set to Routerify but routerify seems to override it even when I set a custom value

**Comment by rousan** [comment]
Hey @NikosEfthias, thanks for pointing out. We should give users an option to overwrite it at least and any fix and PR is welcome.

**Comment by NikosEfthias** [comment]
when it will be possible to have this pr in a release which can be downloaded from crate.io? @rousan

**Comment by rousan** [comment]
I will make a new release today if possible

**Comment by NikosEfthias** [comment]
thanks I guess we can close this now
