### ISSUE TITLE
Using state sharing and access request body

### ISSUE THREAD

**Issue by la-urre** [routerify/routerify#28]
Hello! 

First I want to thank you for this library. I find it easy to use and it suits my needs so far!

I must say I am pretty new to rust development, so my question might be a bit dumb.

I am trying to use state sharing with routerify. I use a struct that contains my database connection pool.

```
pub struct AppState {
    pub connection_pool: Pool
}
```
In my handlers, I get a reference to the AppState like this: `let state = req.data::<AppState>().unwrap()`

The thing is, in my handler I also need to access the request body, and the simplest way I found is to use `
hyper::body::to_bytes(req.into_body())`.

This `into_body` function moves the request variable, so it doesn't play nice with the reference I got for my state. When I try to access `state.connection_pool` I get an error: `cannot move out of 'req' because it is borrowed`. The code is this one:

```
async fn create_competition(req: Request<Body>) -> Result<Response<Body>, RequestParseError> {
    let state = req.data::<AppState>().unwrap();
    let whole_body = hyper::body::to_bytes(req.into_body()).await.map_err(|_| RequestParseError {})?;
    let dto: CreateCompetitionDto = serde_json::from_slice(whole_body).map_err(|_| RequestParseError {})?;
    let competition = Competition { id: Uuid::new_v4(), name: dto.name };
    create_competition(&state.connection_pool, &competition).await.unwrap();
}
```

I might be wrong but I suspect it can be difficult to work with references to the shared state while the request is usually moved (this into_body function is recommended everywhere, and I can't get it work with the body() function). 

What would you recommend me ? Thanks!

**Comment by seanpianka** [comment]
See [this comment](https://github.com/routerify/routerify/issues/26#issuecomment-734012710) and let me know your thoughts.  Don't use `.into_body()`, use `.body_mut()`.

**Comment by la-urre** [comment]
Hello Sean, thanks for your answer.

The code you sent doesn't seem to compile on my side. I reworked it and ended up with:

```
async fn get_request_body<T: DeserializeOwned>(req: &mut Request<Body>) -> Result<T, String> {
    let body = hyper::body::to_bytes(req.body_mut()).await
        .map_err(|_| "internal_server_error".to_string())?;
    serde_json::from_slice(&body)
        .map_err(|e| format!("failed to parse request body: {}", e))
}
```

I know that this is more related to hyper and not Routerify. Still I wonder if it wouldn't help to have an example somewhere. Best place would be on hyper repo directly, I will try to propose one.
Thanks again for your quick response,
Damien
