### ISSUE TITLE
How can I access react req extensions at post middleware?

### ISSUE THREAD

**Issue by NikosEfthias** [routerify/routerify#29]
I am trying to build a logger for my api which logs the endpoint method and time taken.
I am adding a req.extension with a timer however I cant seem to reach it in a post middleware by using res.extension

**Comment by rousan** [comment]
Only one workaround we have right now is to attach a special post middleware with [RequestInfo](https://docs.rs/routerify/1.1.4/routerify/struct.RequestInfo.html) access using [Middleware.post_with_info()](https://docs.rs/routerify/1.1.4/routerify/enum.Middleware.html#method.post_with_info) method and set starting timer value in header in request object in pre-middleware and then access that data in post middleware.

I know it's not an ideal solution, so, I have a plan to add a feature to add any **request-response** lifecycle data in request object and access in response object.

**Comment by NikosEfthias** [comment]
that would be great. I suggest this report be kept open and tagged untill the feature is ready for any people looking for this in the future

**Comment by NikosEfthias** [comment]
btw seems like custom request headers are thrown away because they dont appear in the post middleware with info 
on the attached photo i can see that x-req-start exists but on the inf headers it is simply thrown away 
![image](https://user-images.githubusercontent.com/9097437/102017966-3686ae80-3d7b-11eb-93c2-1f12f3527e0d.png)

**Comment by gsserge** [comment]
What do you guys think about extending `RequestInfo` with a new field `duration: std::time::Duration`? Obtaining the request's duration is quite common for logging and metrics. We could make it conveniently accessible without any special middleware.

However, I also think that we need a more generic mechanism for passing a request's mutable context from pre middlewares, through a handler and all the way down to the post middlewares. Being per request it will complement the global `data` context nicely. However, unlike `data` it should be more dynamic and not restricted to a single generic type. Maybe some kind of generic map from strings to values, although I'm not quite sure how to implement that in Rust.

**Comment by NikosEfthias** [comment]
@gsserge I think duration would be awesome and data part I like things being as strict as possible personally. it prevents me from shooting myself.
A single generic type could be a struct with optional fields i believe so we'd have optional fields while having an awesome completion by the editors also `HashMap<String,Box<dyn MyConvertable>>` seems a lot of work. if a mutable ref to the original req existed in the post middlewares I think that is more than enough since we are able to use request extensions

**Comment by rousan** [comment]
We could extend the [RequestExt](https://docs.rs/routerify/1.1.4/routerify/ext/trait.RequestExt.html) to share data across request handler and middlewares through Request Extension.

```rust
async fn home_handler(req: Request<Body>) -> Result<Response<Body>, io::Error> {
   req.share_data("some-data");
}
```

Then these data will be available to RequestInfo.

**Comment by gsserge** [comment]
> We could extend the [RequestExt](https://docs.rs/routerify/1.1.4/routerify/ext/trait.RequestExt.html) to share data across request handler and middlewares through Request Extension.
> 
> ```rust
> async fn home_handler(req: Request<Body>) -> Result<Response<Body>, io::Error> {
>    req.share_data("some-data");
> }
> ```
> 
> Then these data will be available to RequestInfo.

If I understand correctly, this is a similar approach to #43

**Comment by rousan** [comment]
Sorry, I had missed your recent PR, commenting on that PR.

**Comment by NikosEfthias** [comment]
Sorry seems I missed most of the discussion seems it had been merged. Have you included any documentation somewhere  how to use this feature.I think this is a feature a lot of newcomers who doesnt follow the development would like to see and use off the shelf  @gsserge

**Comment by gsserge** [comment]
@NikosEfthias I've included some examples in the comments for `RequestExt::context()` and `RequestExt::set_context()` methods, as well as for `RequestInfo::context()`. But you're right, I should also expand the `Middleware` and `Data and State Sharing` sections of the documentation in `src/lib.rs`.

**Comment by gsserge** [comment]
Docs and an example are in https://github.com/routerify/routerify/pull/52
