### ISSUE TITLE
At some point routerify panics

### ISSUE THREAD

**Issue by NikosEfthias** [routerify/routerify#36]
```
Jan 15 00:44:41 api2 app[563707]: thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', .cargo/registry/src/github.com-1ecc6299db9ec823/routerify-1.1.4/src/service/request_service.rs:46:16
```
I dont know how exactly to replicate this it just happened out of nowhere and the line causing this seems to be the following 
![image](https://user-images.githubusercontent.com/9097437/104663116-59d7ad00-56dd-11eb-93cf-cc80d4591793.png)

**Comment by NikosEfthias** [comment]
I figured out the issue if the path is invalid routerify fails. So it should first check the path correctness

**Comment by seanpianka** [comment]
Can you add a unit test for this panic? It would be nice to know future changes won't reintroduce this bug.

**Comment by NikosEfthias** [comment]
Hi sorry for the late reply. I will try to add some tests as soon as i can @seanpianka until then we can leave this unclosed i guess
