### ISSUE TITLE
Does routerify need new maintainers?

### ISSUE THREAD

**Issue by NikosEfthias** [routerify/routerify#40]
Seems the version bumps are going pretty slow does the project need more people with merge and publish rights ?

**Comment by rousan** [comment]
New contributors are always welcome, I will send an invitation link if you are interested.

**Comment by NikosEfthias** [comment]
sure it'll be amazing

**Comment by rousan** [comment]
Sent you an invitation.

**Comment by NikosEfthias** [comment]
Accepted.I am not sure how do i get to make point cargo releases tho

**Comment by rousan** [comment]
I will make new releases, just let me know when. Also FYI, we use `develop` branch for new features, bug fixing etc changes. So we need to merge PR to develop branch and when we will release, only then we will merge the stable code to master branch.

**Comment by NikosEfthias** [comment]
Yes I am aware of the flow but without making beta releases how are people gonna test the new features all the bugs I personally found and fixed existed on the crates.io release

**Comment by rousan** [comment]
Yes, We should start making beta releases before pushing stable version. We can adapt `Weekly release cycle`. Whatever we changed in develop branch, we will make a new beta release every week.

**Comment by rousan** [comment]
Just let me know after merging PRs, I will make a new beta release. FYI @NikosEfthias  @seanpianka ,

**Comment by NikosEfthias** [comment]
@rousan My pr was recently merged fixing a panic caused by invalid http headers this is a bug that still exists the release and i encounter a couple hundreds of panics a day because of this issue on production the app is usable because tokio catches panics

**Comment by rousan** [comment]
Got it. @seanpianka, can we make a beta release? Is the develop branch is ready to make a new release?

**Comment by seanpianka** [comment]
More pressing before another release, @rousan can you please send a few minutes and add `/// SAFETY:` comments around the uses of `unsafe` in the current implementation?

I do not feel comfortable being a maintainer for this project as currently Routerify makes frequent use of memory unsafe code. I see no comments showing justification for _why_ the current code is sound, and I cannot see why the current implementation is not unsound.

**Comment by seanpianka** [comment]
Specifically, the [`RequestService`](https://github.com/routerify/routerify/blob/master/src/service/request_service.rs#L10) _must_ be documented with soundness justifications for `*mut Router<B, E>`.

**Comment by rousan** [comment]
Okay, I will do that.

**Comment by seanpianka** [comment]
In the spirit of this, I want to add this clippy lint for this `unsafe` commenting practice: https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc

The idea is to capture the pre, current, and post conditions under which a block of `unsafe` code can be considered safe. #25 raises this concern and attempts to fix it, however there's significant performance loss while doing so. Does that mean we shouldn't accept this change? Is the current implementation fundamentally unsound? No one seems to know. 🙂

**Comment by gsserge** [comment]
@rousan @seanpianka @NikosEfthias hey guys, I think we need to find a way to move the project forward. Look at the open PRs and possibly get them in, **at least** the tokio/hyper update, and then create another beta so that we have something in crates.io. Otherwise, I'm afraid, more people are going to create their own forks and we the project is good to lose on community :( I'd merge the hyper update myself, but I do not have enough permissions.

**Comment by NikosEfthias** [comment]
@gsserge I think it is a great idea and i myself trying to understand how things roll at the moment how things are getting to the crates.io etc. So I guess @rousan could tell us what are rules to get a release on crates.io

**Comment by seanpianka** [comment]
@rousan, please do the following at your earliest convenience:
- Add safety justifications to unsafe code
- Give write access to any other group member

Thanks

**Comment by rousan** [comment]
Hi guys, been very busy on something. Once the required PRs are merged to develop branch, just let me know, I will pull and push to crates.io from my side.

The required checklist for a release:
1. Make sure PRs are merged to develop
2. Check comment docs, update it if needed.
4. then release

**Comment by gsserge** [comment]
@rousan apparently none of us can merge

**Comment by rousan** [comment]
Ok, checking, will give write permissions.

**Comment by rousan** [comment]
I gave write permissions to all the members.

**Comment by gsserge** [comment]
Amazing! Thank you @rousan

**Comment by rousan** [comment]
I am creating a beta-2 release.

**Comment by rousan** [comment]
Released [v2.0.0-beta-2](https://github.com/routerify/routerify/releases/tag/v2.0.0-beta-2)!

**Comment by rousan** [comment]
Hey guys, thanks a lot for the amazing support from your side to make this project more powerful, I really appreciate that. I might not be available for active contributions, but as I gave you all write permissions, so your open thinking and suggestions are always welcome and do not forget to open new PRs and merge them if needed.

**Comment by NikosEfthias** [comment]
@rousan what do you say if we create a irc or telegram channel to communicate more effectively

**Comment by rousan** [comment]
We could do that, but the GitHub has "discussion" section in every repository, so I think we can start with this "discussion" features for now.

**Comment by rousan** [comment]
Here is the link: https://github.com/routerify/routerify/discussions

**Comment by NikosEfthias** [comment]
i wasnt aware of that so lets close this bug report and continue there
