### ISSUE TITLE
Does the paths get resolved in order? 

### ISSUE THREAD

**Issue by kingluo** [routerify/routerify#76]
My question is just like I post an issue for warp, please have a check:
https://github.com/seanmonstar/warp/issues/837

**Comment by gsserge** [comment]
Could you please give an expanded examples of what you are trying to accomplish? It's not very clear from the warp issue.

**Comment by kingluo** [comment]
For example, I bound 1000 URLs via routerify:

```rust
    Router::builder()
        .get("/", home_handler)
        .get("/users/:userId", user_handler)
        ...
```

Then a request comes in, how to resolve the URL into the handler? Serially based on the defined order, or via hash to match just like what Nginx did (first exact match, second prefix match, third regexp match). In the previous case, then it would be slow when the number of URLs is big.

**Comment by gsserge** [comment]
Routerify uses [RegexSet](https://docs.rs/regex/1.5.3/regex/struct.RegexSet.html) to match incoming URLs to registered Routes. There's no linear scan.

[Here](https://github.com/routerify/routerify/blob/master/src/router/mod.rs#L118) is the internal method that constructs a regexset when building a router instance. And [here](https://github.com/routerify/routerify/blob/master/src/router/mod.rs#L118) is where the matching of incoming requests happed. If you look a bit [down](https://github.com/routerify/routerify/blob/master/src/router/mod.rs#L339), the processing stops when the first match (both path and method) is found.

**Comment by kingluo** [comment]
@gsserge how to do the exact match? And, for prefix match, does it return the longest match?

**Comment by gsserge** [comment]
Routerify only does exact match. If multiple routes match, then whatever route is returned by RegexSet first wins. Prefix matches are only performed when sub-routers are defined.

**Comment by kingluo** [comment]
@gsserge The first match is based on the defined order, right? And, any sub-router doc?

**Comment by gsserge** [comment]
I'm not 100% sure, but I think it's based on the defined order. Sub-router, of scoped router, is described right in the docs https://docs.rs/routerify/2.0.1/routerify/#scopingmounting-router

**Comment by kingluo** [comment]
@gsserge Thanks.

**Comment by rousan** [comment]
@kingluo, Routerify uses RegexSet to match the routes, as you can see [here](https://github.com/routerify/routerify/blob/master/src/router/mod.rs#L118), the route paths are being added in RegexSet in order they are defined in the router. Also, any sub routes of scoped router will follow the same.

**Comment by gsserge** [comment]
This should be asked in the warp repo, not here.
