### ISSUE TITLE
Add more organization owners on crates.io

### ISSUE THREAD

**Issue by seanpianka** [routerify/routerify#78]
Hi @rousan, as discussed in #75, could you please add the other Routerify organization members to the crates.io org? This will allow us to more frequently release small improvements. 

Please add myself as an owner of the org, as well as others as you deem appropriate. I believe there's a cargo command for adding new owners:
```
$ cargo owner --help
cargo-owner
Manage the owners of a crate on the registry

USAGE:
    cargo owner [OPTIONS] [--] [crate]

OPTIONS:
    -q, --quiet                    No output printed to stdout
    -a, --add <LOGIN>...           Name of a user or team to invite as an owner
    -r, --remove <LOGIN>...        Name of a user or team to remove as an owner
    -l, --list                     List owners of a crate
        --index <INDEX>            Registry index to modify owners for
        --token <TOKEN>            API token to use when authenticating
...
```
Thanks!

**Comment by rousan** [comment]
@gsserge, @seanpianka, I have changed your role from `member` to `owner` to this Github org, as well as in Cargo org, so that you guys can continue without my availability. Please confirm, if you got these access.
Also, I would suggest to enable **2FA** authentication in Github login for every members.

**Comment by gsserge** [comment]
@rousan thanks! I can confirm ownership in the github org, however not in crates.io

<img width="280" alt="Screenshot 2021-05-06 at 11 12 56" src="https://user-images.githubusercontent.com/241037/117273018-05a73300-ae5c-11eb-9ee6-31538b5ccf69.png">

**Comment by seanpianka** [comment]
I can confirm that I see no pending owner invites on crates.io. @rousan, did you setup your API token for it before adding the owners?

**Comment by rousan** [comment]
@gsserge, @seanpianka, I figured it out, I needed to send request from the crate page. I sent invitations again for every crates owned by Routerify org. Please let me know.

**Comment by gsserge** [comment]
@rousan accepted, thanks!

**Comment by rousan** [comment]
Regarding release process, I am using a very helpful tool named [releez](https://github.com/rousan/releez) to automate the release process. The release checklist is written in the `releez.yml` file.

You only need to install the tool from the given link and run:
```sh
$ releez <release_version>
```
It will run the testcases, format the codes and release the tags in Github, as well as to crates.io.

**Comment by seanpianka** [comment]
I think everything necessary for this issue has been resolved. Thanks all!
