### ISSUE TITLE
releez.yml fails if git-flow is not installed

### ISSUE THREAD

**Issue by seanpianka** [routerify/routerify#79]
Following the steps mentioned [here](https://github.com/routerify/routerify/issues/78#issuecomment-834115454), releasing a new version using `releez` will fail due to the git-flow git extension not being installed locally.

```
$ releez 2.0.2
...
Checked: Run tests

Running: Start a new release branch

$ git flow release start "v${VERSION}"
git: 'flow' is not a git command. See 'git --help'.

The most similar commands are
	reflog
	show

error: Failed to execute auto task command: 'git flow release start "v${VERSION}"' with exit code: '1' for task: 'Start a new release branch'
```

Perhaps the `releez.yml` should include a step to install git-flow for the platform? Platform-specific steps are listed [in this cheatsheet](https://danielkummer.github.io/git-flow-cheatsheet/) I found.

Edit: Additionally, after manually installing the extension, `git flow release start ...` fails with:
```
$ git flow release start "v${VERSION}"
Fatal: Not a gitflow-enabled repo yet. Please run 'git flow init' first.

error: Failed to execute auto task command: 'git flow release start "v${VERSION}"' with exit code: '1' for task: 'Start a new release branch'
```
Should certain git-flow files get committed? `git flow init` asks many questions which likely need to remain consistent across hosts:
```
$ git flow init
Which branch should be used for bringing forth production releases?
   - develop
   - fixup-requestservicebuilder
   - master
   - update-readme-features
Branch name for production releases: [master]

Which branch should be used for integration of the "next release"?
   - develop
   - fixup-requestservicebuilder
   - update-readme-features
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? [feature/]
Bugfix branches? [bugfix/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
...
```

**Comment by rousan** [comment]
Yes, `git-flow` is needed to make new release branches. Just run `git flow init` for first time and accept default values.

**Comment by rousan** [comment]
@seanpianka, I just noticed the new version `v2.0.2 is pushed to Github, but not released in crates.io. The `releez` tool might not run properly.

**Comment by seanpianka** [comment]
Hi @rousan, this should be resolved now, I noticed it soon after it failed for me locally :)

**Comment by seanpianka** [comment]
This issue can serve as documentation in-case @gsserge runs into this issue when releasing a new version 🙂
