### ISSUE TITLE
RequestExt on http::request::Parts

### ISSUE THREAD

**Issue by lucacasonato** [routerify/routerify#80]
Once you turn a `http::Request` into `http::request::Parts` and `hyper::Body` using `Request::into_parts`, you lose the ability to get / set state and data from the request. It would be awesome if the same extensions from the `RequestExt` could also be added to `http::request::Parts` via means of a `RequestPartsExt`.

**Comment by gsserge** [comment]
Great idea! I never noticed that the extensions are defined on `head: Parts`, not the `Request` itself. This can definitely help when you need to consume a request (e.g. json payload) but still use data, params or context. At the moment the only solution is cloning, and that is not ideal.

Would you be willing to contribute the PR? :)

**Comment by lucacasonato** [comment]
> Would you be willing to contribute the PR? :) 

Sure!

**Comment by gsserge** [comment]
Merged, thanks! I will create a new release this weekend.
