### ISSUE TITLE
Use minimal set of dependency features

### ISSUE THREAD

**Issue by danielnelson** [routerify/routerify#97]
I'm just getting started with routerify and I love how lightweight it is while providing the features I need.  I'm not an expert on cargo dependencies, but it seems that it would be possible to be even more lightweight if the dependency features were restricted down to what is actually required.

For hyper we currently have:
```
hyper = { version = "0.14", default-features = false, features = ["full"] }
```

But from my testing it could be:
```
hyper = { version = "0.14", default-features = false, features = ["server", "tcp", "http1"] }
```

It would be possible to have either `http1` or `http2`, so long as one is set, though I don't know a way this could represented in Cargo.  Enabling `http1` does not bring in any new dependencies to hyper.

With regex we use the default features:
```
regex = "1"
```

But we can compile with:
```
regex = { version = "1", default-features = false, features = ["std"] }
```

I think changing regex features could cause problems if we are compiling regex that are passed in as strings.  It may be required to add an new feature that can enable them:
```
[features]
default = ["regex/default"]
```

If we made these changes it would bring the example program in the main README.md down from 63 to 51 dependencies and reduce the release binary when stripped from 3.2M to 1.5M.

I'm not confident on what the versioning ramification would be for this change, but there is some guidance here:
- https://doc.rust-lang.org/cargo/reference/semver.html#major-removing-a-feature-from-a-feature-list-if-that-changes-functionality-or-public-items
- https://doc.rust-lang.org/cargo/reference/semver.html#cargo-change-dep-feature#cargo-change-dep-feature

**Comment by seanpianka** [comment]
@danielnelson Can this issue be closed now that the MR is merged?

**Comment by danielnelson** [comment]
Yes, thanks again.
