### ISSUE TITLE
Logging RouteError

### ISSUE THREAD

**Issue by Selyatin** [routerify/routerify#98]
I was wondering if there's a way to actually log the error on server side too rather than just sending it to the client?

**Comment by gsserge** [comment]
If you only want to log an error, you can use [err_handler_with_info](https://docs.rs/routerify/2.2.0/routerify/struct.RouterBuilder.html#method.err_handler_with_info). Routerify has no opinion on logging, so just use your favourite logger here.

```rust
Router::builder()
        .get("/", index)
        .err_handler_with_info(|err: RouteError, req_info: RequestInfo| {
                error!("Error: {:?}", err);
                // Convert error to the response code or something...
                let resp = ...;
         })
        .build()
```
