### ISSUE TITLE
Example from documentation doesn't work.

### ISSUE THREAD

**Issue by iupii** [routerify/routerify#99]
error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> src/main.rs:64:10
   |
64 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0599]: no method named `data` found for struct `Request` in the current scope
  --> src/main.rs:13:21
   |
13 |     let state = req.data::<State>().unwrap();
   |                     ^^^^ method not found in `Request<Body>`
   |
  ::: /Users/y.pachin/.cargo/registry/src/github.com-1ecc6299db9ec823/http-body-0.3.1/src/lib.rs:72:8
   |
72 |     fn data(&mut self) -> Data<'_, Self>
   |        ---- the method is available for `Request<Body>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use hyper::body::HttpBody;
   |

error[E0599]: no method named `param` found for struct `Request` in the current scope
  --> src/main.rs:21:23
   |
21 |     let user_id = req.param("userId").unwrap();
   |                       ^^^^^ method not found in `Request<Body>`

error[E0599]: no method named `remote_addr` found for struct `Request` in the current scope
  --> src/main.rs:29:13
   |
29 |         req.remote_addr(),
   |             ^^^^^^^^^^^ method not found in `Request<Body>`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:69:38
   |
69 |     let service = RouterService::new(router).unwrap();
   |                                      ^^^^^^ the trait `http_body::Body` is not implemented for `Body`
   |
   = note: required by `RouterService::<B, E>::new`

error[E0277]: the trait bound `for<'a> RouterService<Body, Infallible>: Service<&'a AddrStream>` is not satisfied
  --> src/main.rs:75:44
   |
75 |     let server = Server::bind(&addr).serve(service);
   |                                            ^^^^^^^ the trait `for<'a> Service<&'a AddrStream>` is not implemented for `RouterService<Body, Infallible>`
   |
   = help: the following implementations were found:
             <RouterService<B, E> as Service<&hyper::server::tcp::addr_stream::AddrStream>>
   = note: required because of the requirements on the impl of `hyper::service::make::MakeServiceRef<AddrStream, Body>` for `RouterService<Body, Infallible>`

error[E0277]: the trait bound `for<'a> RouterService<Body, Infallible>: Service<&'a AddrStream>` is not satisfied
  --> src/main.rs:78:23
   |
78 |     if let Err(err) = server.await {
   |                       ^^^^^^^^^^^^ the trait `for<'a> Service<&'a AddrStream>` is not implemented for `RouterService<Body, Infallible>`
   |
   = help: the following implementations were found:
             <RouterService<B, E> as Service<&hyper::server::tcp::addr_stream::AddrStream>>
   = note: required because of the requirements on the impl of `hyper::service::make::MakeServiceRef<AddrStream, Body>` for `RouterService<Body, Infallible>`
   = note: required because of the requirements on the impl of `Future` for `Server<AddrIncoming, RouterService<Body, Infallible>>`
   = note: required by `poll`

error[E0277]: the trait bound `RouterService<Body, Infallible>: Service<&'a AddrStream>` is not satisfied
  --> src/main.rs:75:38
   |
75 |     let server = Server::bind(&addr).serve(service);
   |                                      ^^^^^ the trait `Service<&'a AddrStream>` is not implemented for `RouterService<Body, Infallible>`
   |
   = help: the following implementations were found:
             <RouterService<B, E> as Service<&hyper::server::tcp::addr_stream::AddrStream>>
   = note: required because of the requirements on the impl of `hyper::service::make::MakeServiceRef<AddrStream, Body>` for `RouterService<Body, Infallible>`

error[E0631]: type mismatch in function arguments
  --> src/main.rs:56:37
   |
26 | async fn logger(req: Request<Body>) -> Result<Request<Body>, Infallible> {
   | ------------------------------------------------------------------------ found signature of `fn(Request<Body>) -> _`
...
56 |         .middleware(Middleware::pre(logger))
   |                                     ^^^^^^ expected signature of `fn(Request<hyper::body::body::Body>) -> _`
   |
  ::: /Users/y.pachin/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-2.2.0/src/middleware/mod.rs:52:70
   |
52 |         R: Future<Output = Result<Request<hyper::Body>, E>> + Send + 'static,
   |                                                                      ------- required by this bound in `Middleware::<B, E>::pre`

error[E0631]: type mismatch in function arguments
  --> src/main.rs:57:19
   |
11 | async fn home_handler(req: Request<Body>) -> Result<Response<Body>, Infallible> {
   | ------------------------------------------------------------------------------- found signature of `fn(Request<Body>) -> _`
...
57 |         .get("/", home_handler)
   |                   ^^^^^^^^^^^^ expected signature of `fn(Request<hyper::body::body::Body>) -> _`

error[E0631]: type mismatch in function arguments
  --> src/main.rs:58:32
   |
20 | async fn user_handler(req: Request<Body>) -> Result<Response<Body>, Infallible> {
   | ------------------------------------------------------------------------------- found signature of `fn(Request<Body>) -> _`
...
58 |         .get("/users/:userId", user_handler)
   |                                ^^^^^^^^^^^^ expected signature of `fn(Request<hyper::body::body::Body>) -> _`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:52:5
   |
52 |     Router::builder()
   |     ^^^^^^^^^^^^^^^ the trait `http_body::Body` is not implemented for `Body`
   |
   = note: required by `Router::<B, E>::builder`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:55:10
   |
55 |         .data(State(100))
   |          ^^^^ the trait `http_body::Body` is not implemented for `Body`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:56:10
   |
56 |         .middleware(Middleware::pre(logger))
   |          ^^^^^^^^^^ the trait `http_body::Body` is not implemented for `Body`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:56:21
   |
56 |         .middleware(Middleware::pre(logger))
   |                     ^^^^^^^^^^^^^^^ the trait `http_body::Body` is not implemented for `Body`
   |
  ::: /Users/y.pachin/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-2.2.0/src/middleware/mod.rs:51:12
   |
51 |         H: Fn(Request<hyper::Body>) -> R + Send + Sync + 'static,
   |            ----------------------------- required by this bound in `Middleware::<B, E>::pre`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:57:10
   |
57 |         .get("/", home_handler)
   |          ^^^ the trait `http_body::Body` is not implemented for `Body`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:58:10
   |
58 |         .get("/users/:userId", user_handler)
   |          ^^^ the trait `http_body::Body` is not implemented for `Body`

error[E0277]: the trait bound `Body: http_body::Body` is not satisfied
  --> src/main.rs:59:10
   |
59 |         .err_handler_with_info(error_handler)
   |          ^^^^^^^^^^^^^^^^^^^^^ the trait `http_body::Body` is not implemented for `Body`

error[E0599]: the method `build` exists for struct `RouterBuilder<Body, _>`, but its trait bounds were not satisfied
  --> src/main.rs:60:10
   |
60 |         .build()
   |          ^^^^^ method cannot be called on `RouterBuilder<Body, _>` due to unsatisfied trait bounds
   |
  ::: /Users/y.pachin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/body/body.rs:28:1
   |
28 | pub struct Body {
   | --------------- doesn't satisfy `Body: http_body::Body`
   |
   = note: the following trait bounds were not satisfied:
           `Body: http_body::Body`

warning: unused import: `routerify::prelude`
 --> src/main.rs:3:5
  |
3 | use routerify::prelude::*;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0752]: `main` function is not allowed to be `async`
  --> src/main.rs:65:1
   |
65 | async fn main() {
   | ^^^^^^^^^^^^^^^ `main` function is not allowed to be `async`

**Comment by gsserge** [comment]
Make sure that you have all required dependencies in your `Cargo.toml` as specified in the `Install` section of the repo's `README.md`

```toml
[dependencies]
routerify = "2"
hyper = "0.14"
tokio = { version = "1", features = ["full"] }
```
